default: &default
  adapter: postgresql
  encoding: unicode
  username: zanetagebka
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 30 } %>

development:
  <<: *default
  database: petfinder_development

test:
  <<: *default
  database: petfinder_test